### ISSUE TITLE
dataset is missing?

### ISSUE THREAD

**Issue by SeekPoint** [ApoGouv/Big-Data-Link-Prediction#1]

**Comment by SeekPoint** [comment]
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$ python predictions_with_BC.py 
 /!\ Script Starting execution @:  22:19:28  /!\ 
Traceback (most recent call last):
  File "predictions_with_BC.py", line 15, in <module>
    training_features_scaled = np.loadtxt('out-after-features/training_features_scaled.txt', dtype=np.float64)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 896, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'out-after-features/training_features_scaled.txt'
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$ python predictions_with_GBC.py 
 /!\ Script Starting execution @:  22:19:48  /!\ 
Traceback (most recent call last):
  File "predictions_with_GBC.py", line 15, in <module>
    training_features_scaled = np.loadtxt('out-after-features/training_features_scaled.txt', dtype=np.float64)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 896, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: 'out-after-features/training_features_scaled.txt'
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$ git remote -v
origin	https://github.com/ApoGouv/Big-Data-Link-Prediction (fetch)
origin	https://github.com/ApoGouv/Big-Data-Link-Prediction (push)
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$

**Comment by ApoGouv** [comment]
Hello, 
if you are referring to this error " No such file or directory: 'out-after-features/training_features_scaled.txt'"
the "training_features_scaled.txt" file is included in the repo, just make sure you have downloaded.

**Comment by SeekPoint** [comment]
No, it doesn't

mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$ ll out-after-features/
total 24336
drwxrwxr-x 2 mldl mldl     4096 9月  23 22:00 ./
drwxrwxr-x 6 mldl mldl     4096 9月  23 22:00 ../
-rw-rw-r-- 1 mldl mldl 12310250 9月  23 22:00 labels_array.txt
-rw-rw-r-- 1 mldl mldl 12597901 9月  23 22:00 testing_features_scaled.txt
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$

**Comment by ApoGouv** [comment]
ohh! Sorry about that, you are right (I haven't looked at this project for a year now).
I had to make a search into the code and the "missing" file is generated if you run the "calculate_features.py" file.
