### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Graph'

### ISSUE THREAD

**Issue by SeekPoint** [ApoGouv/Big-Data-Link-Prediction#2]
I have to change igraph to hgraph , however:

mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$ python calculate_features.py
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
.
.
.
.

      ['1005', '2000', 'bundles of chiral blocks and boundary conditions in cft', 'J. Fuchs, C. Schweigert', '', 'proceedings of lie iii clausthal july 1999 various aspects of spaces of chiral blocks are discussed in particular conjectures about the dimensions of irreducible sub-bundles are reviewed and their relation to symmetry breaking conformal boundary conditions is outlined']
Traceback (most recent call last):
  File "calculate_features.py", line 199, in <module>
    g = jgraph.Graph(directed=True)
AttributeError: 'module' object has no attribute 'Graph'
mldl@ub1604:~/ub16_prj/Big-Data-Link-Prediction/src$

**Comment by ApoGouv** [comment]
This probably has to do with your setup
http://bfy.tw/K1Ym
